vim.api.nvim_set_keymap('', '<C-q>', '<Cmd>BufferWipeout<CR>', { noremap = true })
vim.api.nvim_set_keymap('i', '<C-q>', '<Esc><Cmd>BufferWipeout<CR>', { noremap = true })
vim.api.nvim_set_keymap('', '<A-q>', '<Cmd>tabclose<CR>', { noremap = true })
vim.api.nvim_set_keymap('i', '<A-q>', '<Esc><Cmd>tabclose<CR>', { noremap = true })

vim.api.nvim_set_keymap('', '<C-x>', '<Cmd>w<CR><Cmd>BufferWipeout<CR>', { noremap = true })
vim.api.nvim_set_keymap('i', '<C-x>', '<Esc><Cmd>w<CR><Cmd>BufferWipeout<CR>', { noremap = true })
vim.api.nvim_set_keymap('', '<A-x>', '<Cmd>w<CR><Cmd>tabclose<CR>', { noremap = true })
vim.api.nvim_set_keymap('i', '<A-x>', '<Esc><Cmd>w<CR><Cmd>tabclose<CR>', { noremap = true })

vim.api.nvim_set_keymap('', ']b', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferNext<CR>', { noremap = true })
vim.api.nvim_set_keymap('', '[b', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferPrevious<CR>', { noremap = true })
vim.api.nvim_set_keymap('', '<A-]>', '<Cmd>BufferMoveNext<CR>', { noremap = true })
vim.api.nvim_set_keymap('', '<A-[>', '<Cmd>BufferMovePrevious<CR>', { noremap = true })

vim.api.nvim_set_keymap('n', '<A-1>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 1<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-2>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 2<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-3>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 3<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-4>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 4<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-5>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 5<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-6>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 6<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-7>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 7<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-8>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferGoto 8<CR>', { noremap = true })
vim.api.nvim_set_keymap('n', '<A-9>', '<Cmd>SwitchToNormalBuffer<CR><Cmd>BufferLast<CR>', { noremap = true })

vim.api.nvim_set_keymap('', 'Q', '<Cmd>BufferCloseAllButCurrent<CR>', { noremap = true })
vim.api.nvim_set_keymap('', '<Backspace>', '<Cmd>BufferPick<CR>', { noremap = true })

vim.cmd('highlight link BufferCurrentSign String')
vim.cmd('highlight link BufferCurrent String')
vim.cmd('highlight link BufferVisible lualine_a_normal')
vim.cmd('highlight link BufferVisibleSign lualine_a_normal')
